services:
  pgadmin:
    image: dpage/pgadmin4:8.9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: dev      
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db

  db:
    image: postgres:12.19
    restart: always          
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:                 
      - pg-data:/var/lib/postgresql/data

volumes:
  pgadmin-data:
  pg-data: